#!/usr/bin/env php

<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use App\Commands\GetNextValidDrawCommand;
use App\Commands\GetNextValidDrawCommandBasedOnCurrentDate;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new GetNextValidDrawCommandBasedOnCurrentDate());
$application->add(new GetNextValidDrawCommand());

$application->run();
